### ISSUE TITLE
Utilize `allowedNodeEnvironmentFlags`

### ISSUE THREAD

**Issue by phated** [gulpjs/v8flags#51]
Post node 10.10 - https://nodejs.org/api/process.html#process_process_allowednodeenvironmentflags

**Comment by AequoreaVictoria** [comment]
Any idea when this might land? This v8flags library has blocked me from using gulp 4.0 for a cross-platform build script since on Windows it does essentially randomly named writes for its cache file and I cannot disable it. This in turn breaks another build tool (tup) I am using that needs to have all writes documented prior to execution. Oddly enough it doesn't do this on Linux.

Regardless, everything works fine when I stick to the 3.x release, other than the npm audit warnings. It'd be great if I could finally move to 4.0.

**Comment by phated** [comment]
I just checked this in node 10.15 and it doesn't actually provide v8 flags, it only shows node-specific flags.  I don't think we'll be able to get all the information we need from here.

@AequoreaVictoria doesn't it write into your home directory?  You can also set environment variables to get it to write somewhere else.  So that shouldn't be a blocker from you using gulp 4.

**Comment by AequoreaVictoria** [comment]
@phated Absolutely unacceptable for my case. It should not be writing any additional files at all and until this is corrected I simply can't use gulp 4.

**Comment by phated** [comment]
gulp v3 writes to the filesystem as well. Sorry to hear you have such constraints.

**Comment by phated** [comment]
In #55, we got support for node flags as well. Once this project is node 10+, we can swap that exec with this API.
